language: node_js
node_js:
  - "6.5"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "eS+5HtvzZN8olOgY0WNEwVDcGLFRb3ygys1+IVtR/9detGMa9q8oRc81z8TYsDeDKHbs2lSAMUuTP5eu9khwgRo5IAMo6voNnMyhDftAK+p5JkBo+SsDuAlbTcte1Bvqr2O1AfdT+Ew4GpbWuHpnSGSFu0PcbR4JjdKrhTsnEXqutynhqbjMv2vD6U1rrj2JWMs1LR+fopDKiGQvHiMU6vJmSnrBC4/NSCfiB44FnpFVF1Hh149NpAfsJ4ImtpRsLou4wxNRK9rEv/YGLEq2EFjVKxgHg6tm9K8qMo5rRG4EAfbI6D/ttBogLWVpyJwAMLkiFtMXy+/AclCeFWv4UGfYJOXVFSe4aBRorysqlt8B3MznuQgkhmAuf7YjAEFlRE6GBJqdc4bIeA69G64JOwpZkoTFPwMV55YePvz5ErrqJ5xF47RbQoZ5QITlIwAjRKzPeautJQFT8ODhrupIUHnkA9n3WW8IXZnwvR/mhYRqfOKtBkQYlEK6msoDXgJn+5tGvtsUQ8phB+O4Enog6xLqh7tUPEEzIWVswzpRKl29fFvSPR+9WPea6ONAJr8DwPct2D3fiFWNxlOLmAGdJ0lwRgLMgxMqq/rGYqzkw8HWFpVlXR5YuuQSLatmq7+OkRWM8PTvrpoVSfmg8I1o4QEhv0OJnTehrxLgcgk5tTw="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
